name: CI

on:
  push:
  pull_request:

jobs:
  build images:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: build images
        run: docker compose build