name: CI

on:
  push:
  pull_request:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: build images
        run: docker compose build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: setup python on vm
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: installing ruff
        run: pip install ruff
      - name: lint blog app and activity service
        run: ruff check blog_app activity_service --select E9,F63,F7,F82